// Auto-generated by tools/generate-mappers.ts
import { news, Prisma } from "@prisma/client";
import { NewsEntity } from "../../entities";

export class NewsMapper {
  static prismaToEntity(model: Prisma.newsGetPayload<{}>): NewsEntity {
    const mapped: NewsEntity = {
      id: model.id !== null && model.id !== undefined ? model.id.toString() : '',
      title: model.title !== null && model.title !== undefined ? model.title.toString() : '',
      subTitle: model.subTitle !== null && model.subTitle !== undefined ? model.subTitle.toString() : '',
      content: model.content !== null && model.content !== undefined ? model.content.toString() : '',
      image: model.image !== null && model.image !== undefined ? model.image.toString() : '',
    };

    return mapped;
  }

  static entityToPrisma(entity: NewsEntity): news {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      title: entity.title as any,
      subTitle: entity.subTitle as any,
      content: entity.content as any,
      image: entity.image as any,
    } as news;
  }
}

export default NewsMapper;
