// Auto-generated by tools/generate-mappers.ts
import { users, Prisma } from "@prisma/client";
import { UsersEntity } from "../../entities";

export class UsersMapper {
  static prismaToEntity(model: Prisma.usersGetPayload<{}>): UsersEntity {
    const mapped: UsersEntity = {
      id: model.id !== null && model.id !== undefined ? model.id.toString() : '',
      email: model.email !== null && model.email !== undefined ? model.email.toString() : '',
      password: model.password !== null && model.password !== undefined ? model.password.toString() : '',
    };

    return mapped;
  }

  static entityToPrisma(entity: UsersEntity): users {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      email: entity.email as any,
      password: entity.password as any
    } as users;
  }
}

export default UsersMapper;
